#########################################################################
######################### Novos Endpoints ###############################
#########################################################################

######################### Produtos Service ################################
### GET All Ultimo Valor dos Sensores por Tipo
GET http://localhost:3001/backend/api/produtos
Accept: application/json

######################### Clientes Service ################################
### GET All clientes
GET http://localhost:3001/backend/api/clientes
Accept: application/json

######################### Encomenda Service ################################
### Get All Encomenda
GET http://localhost:3001/backend/api/encomendas/
Accept: application/json

### Get Encomenda Por Id
GET http://localhost:3001/backend/api/encomendas/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTQwMzA2MCwiZXhwIjoxNzM1NDA2NjYwfQ.hpIDTlnrv3BAJfUEtGyf7ybEp2Ir4qRR9tTal-Ae-66XJgf4BmR7y61zFZnpfvOd

### Get All Encomendas por um determinado estado "PorEntregar" "Cancelada" "EmProcessamento" "Entregue"
GET http://localhost:3001/backend/api/encomendas/estado/EmProcessamento
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTQxMTQxOCwiZXhwIjoxNzM1NDE1MDE4fQ.ZRynXHlPr67EL-vlIx7cJZYqj2ChXKA91tjRh_f6M37nQUyn6f7oVH0eMVV16dHB


### Get Encomendas Pendentes
GET http://localhost:3001/backend/api/encomendas/pendentes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM1NDExNjM5LCJleHAiOjE3MzU0MTUyMzl9.6aFCp7xy1PWYaKNVt8flWcg_iP7rtpjSStevnco0q10gItG4adn3sGOWZ3Qih7ai

### Alterar estado de uma encomenda #
PATCH http://localhost:3001/backend/api/encomendas/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzU0MTQyNDMsImV4cCI6MTczNTQxNzg0M30.LFteKubgp_93R6rMMJlOobvNGvZA9jnjS7krERFEccwIWU5bBAfGq4gg4JbRSrIu


{
  "estado": "PorEntregar"
}

###Criar uma nova encomenda #
POST http://localhost:3001/backend/api/encomendas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTQwMzA2MCwiZXhwIjoxNzM1NDA2NjYwfQ.hpIDTlnrv3BAJfUEtGyf7ybEp2Ir4qRR9tTal-Ae-66XJgf4BmR7y61zFZnpfvOd
Content-Type: application/json

{
  "username": "Bernardo",
  "data_expedicao": "2024-10-31T10:00:00",
  "volumes": [
    {
      "produtos": [
        {
          "id": 1,
          "quantidade_de_produtos_comprados": 10
        },
        {
          "id": 2,
          "quantidade_de_produtos_comprados": 10
        }
      ]
    },
    {
      "produtos": [
        {
          "id": 1,
          "quantidade_de_produtos_comprados": 10
        }
      ]
    }
  ]
}

### Associar um volume a uma encomenda
POST http://localhost:3001/backend/api/encomendas/6/volume
Accept: application/json
Content-Type: application/json

{
  "id_produto": 7,
  "quantidade": 2
}

### Get All Alertas de Encomenda por Id #
GET http://localhost:3001/backend/api/encomendas/1/alertas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTQxMTQxOCwiZXhwIjoxNzM1NDE1MDE4fQ.ZRynXHlPr67EL-vlIx7cJZYqj2ChXKA91tjRh_f6M37nQUyn6f7oVH0eMVV16dHB


### GET Ver Alertas de encomendas (PorEntregar) #
GET http://localhost:3001/backend/api/encomendas/alertas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzU0MTIxNDcsImV4cCI6MTczNTQxNTc0N30.RSQg5JxgcXdENeIXLbe_GauYG5FZoQRIY9QbKD8mmXz-v5nqUr0fiiMCyH8tWr0-


### Get Coordenadas Volumes
GET http://localhost:3001/backend/api/encomendas/1/coordenadas
Accept: application/json

######################### Volume Service ################################

### Get Detalhes Volume
GET http://localhost:3001/backend/api/volume/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTQxMzI2MywiZXhwIjoxNzM1NDE2ODYzfQ.YOUCQvaUZsQKaKdeapa7mgRApuvCXvt3aeMxVDYHOs174XfnPfHwAVHwO7qz1tKY

###Associar um Sensor a um Embalagem
POST http://localhost:3001/backend/api/embalagem/1/sensor
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTQxMzI2MywiZXhwIjoxNzM1NDE2ODYzfQ.YOUCQvaUZsQKaKdeapa7mgRApuvCXvt3aeMxVDYHOs174XfnPfHwAVHwO7qz1tKY
Content-Type: application/json

{
  "valor": 90,
  "tipoId": 4,
  "estado": "ativo",
  "bateria": 72
}

################################ Sensor Service ################################

### Get All sensores #
GET http://localhost:3001/backend/api/sensor/
Accept: application/json

### Criar um alerta #
POST http://localhost:3001/backend/api/sensor/
Accept: application/json
Content-Type: application/json

{
  "mensagem": "Temperatura elevada, aaaacomida a estragar-se",
  "id_sensor": 5,
  "valor": 40,
  "id_volume": 4
}

### Patch Sensor Estado #
PATCH http://localhost:3001/backend/api/sensor/2/desativar
Accept: application/json
Content-Type: application/json

{
  "estado": "inativo"
}

### Patch Sensor Valor #
PATCH http://localhost:3001/backend/api/sensor/1
Accept: application/json
Content-Type: application/json

{
  "valor": "26.5",
  "bateria": 72
}

### Get All Tipos de Sensor #
GET http://localhost:3001/backend/api/sensor/tipos
Accept: application/json

### GET All Ultimo Valor dos Sensores por Tipo #
GET http://localhost:3001/backend/api/sensor/Temperatura
Accept: application/json

### GET Ver Alertas de um sensor #
GET http://localhost:3001/backend/api/sensor/1/alertas
Accept: application/json

################################ End Points Login ################################

### REQUEST JWT TOKEN
POST http://localhost:3001/backend/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Miguel", "password": "123" }

### GET User Info
GET http://localhost:3001/backend/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTIyNTg3NiwiZXhwIjoxNzM1MjI5NDc2fQ.D5vp08BndFDGMP2gLTYWbJjKy-CDJDROpK4Tg75FwjHbgmR2HocGg5qSUTK4cbSv