#########################################################################
######################### Novos Endpoints ###############################
#########################################################################

######################### Produtos Service ################################
### GET All Produtos #
GET http://localhost:3001/backend/api/produto
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDIyMjksImV4cCI6MTczNzIwNTgyOX0.VAXofaAz7AJ3JhvruAc0zhDOUaLT0C9oneQSdWyWcYZ60J7QmknPDZo15CA0fAg5

######################### Clientes Service ################################
### GET All clientes #
GET http://localhost:3001/backend/api/cliente
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDIyMjksImV4cCI6MTczNzIwNTgyOX0.VAXofaAz7AJ3JhvruAc0zhDOUaLT0C9oneQSdWyWcYZ60J7QmknPDZo15CA0fAg5

######################### Encomenda Service ################################
### Get All Encomenda #
GET http://localhost:3001/backend/api/encomenda
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNzE5OTY2NSwiZXhwIjoxNzM3MjAzMjY1fQ.yG7LDrAYxkviSp5X_ghg_9qBtM28nP_9ltUybwKepJ8HVMcjP3mNuugrs-xicFVw

### Get Encomenda Por Id #
GET http://localhost:3001/backend/api/encomenda/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNzE5OTY2NSwiZXhwIjoxNzM3MjAzMjY1fQ.yG7LDrAYxkviSp5X_ghg_9qBtM28nP_9ltUybwKepJ8HVMcjP3mNuugrs-xicFVw

### Get All Encomendas por um determinado estado "PorEntregar" "Cancelada" "EmProcessamento" "Entregue" #
GET http://localhost:3001/backend/api/encomenda/estado/Cancelada
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDAxNTksImV4cCI6MTczNzIwMzc1OX0.L25ZEwyK6bVpug9xLrKdVeRB9wfPoJ2AqotfbPYnViehVRuJIg6uljQf0xZCMjvJ

### Alterar estado de uma encomenda #
PATCH http://localhost:3001/backend/api/encomenda/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM1NTc1MTg2LCJleHAiOjE3MzU1Nzg3ODZ9.zIIIFVEKQzfVI4OzewVeUNtoRPpRhB4LgCnbUFoW0HcQCHQEYSK1l3IihWYN9YN0
Content-Type: application/json

{
  "estado": "Entregue"
}

###Criar uma nova encomenda #
POST http://localhost:3001/backend/api/encomenda
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcwNzA1OTAsImV4cCI6MTczNzA3NDE5MH0.wvhj0bO_a3LZD3opgFDLdp4gsVwo4uI4ErrvV-NSyMrryp6PA2K9L-6pWHMbSD6i
Content-Type: application/json

{
  "id": 100,
  "username": "Bernardo",
  "volumes": [
    {
      "id": 100,
      "embalagens": [
        {
          "id": 105,
          "produto": {
            "id": 1
          },
          "tipo" : 1,
          "quantidade": 8
        },
        {
          "id": 106,
          "produto": {
            "id": 5
          },
          "tipo" : 2,
          "quantidade": 8
        }
      ]
    },
    {
      "id": 101,
      "embalagens": [
        {
          "id": 107,
          "produto": {
            "id": 1
          },
          "tipo" : 1,
          "quantidade": 8
        },
        {
          "id": 108,
          "produto": {
            "id": 5
          },
          "tipo" : 2,
          "quantidade": 8
        }
      ]
    }
  ]
}

### Associar um Volume a uma Encomenda #
POST http://localhost:3001/backend/api/encomenda/2/volume
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMTAxMzUsImV4cCI6MTczNzIxMzczNX0.HZOsKRrjaXf1dPEGR3VelmekqK-Y1ModZGT81eKFtDVeCY2HYLSqDsYT5HD2qEHL
Content-Type: application/json

{
  "id": 110,
      "embalagens": [
        {
          "id": 111,
          "produto": {
            "id": 1
          },
          "tipo" : 10,
          "quantidade": 8
        },
        {
          "id": 110,
          "produto": {
            "id": 5
          },
          "tipo" : 4,
          "quantidade": 8
        },
        {
          "id": 112,
          "produto": {
            "id": 5
          },
          "tipo" : 10,
          "quantidade": 8
        },
        {
          "id": 113,
          "produto": {
            "id": 10
          },
          "tipo" : 7,
          "quantidade": 7
        }
      ]
}

### Get All Alertas de Encomenda por Id #
GET http://localhost:3001/backend/api/encomenda/1/alerta
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDAxNTksImV4cCI6MTczNzIwMzc1OX0.L25ZEwyK6bVpug9xLrKdVeRB9wfPoJ2AqotfbPYnViehVRuJIg6uljQf0xZCMjvJ


### GET Ver Alertas de encomendas (PorEntregar) #
GET http://localhost:3001/backend/api/encomenda/alerta
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM3MjAzMDg4LCJleHAiOjE3MzcyMDY2ODh9.RU_Ew3_XIo9JLz1yfCEctWRYvaPSYHt6oSRltuo3Ddfsx8NuY1JkMxDcuYcSxCqi

### Get Coordenadas Volumes #
GET http://localhost:3001/backend/api/encomenda/1/coordenada
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM3MjAzMDg4LCJleHAiOjE3MzcyMDY2ODh9.RU_Ew3_XIo9JLz1yfCEctWRYvaPSYHt6oSRltuo3Ddfsx8NuY1JkMxDcuYcSxCqi

####################´´##### Volume Service ################################

### Get Detalhes Volume #
GET http://localhost:3001/backend/api/volume/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNzIwMTc4MSwiZXhwIjoxNzM3MjA1MzgxfQ.oQT2BTmypwxiDzmRr7hyqxWHGqH-l_0AtN6OsBYGJWeEYPFHLkxRjqFVzEPlGfr4

### Entregar Volume
PATCH http://localhost:3001/backend/api/volume/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDcwNjIsImV4cCI6MTczNzIxMDY2Mn0.powHcH0hr3e-CURlFABjmaTKtBFWWjD5Vd6_oA8v3f83swMKhfLo2f48tJL_s-hP


###Associar um Sensor a um Embalagem #
POST http://localhost:3001/backend/api/embalagem/5/sensor
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDE1MzAsImV4cCI6MTczNzIwNTEzMH0.sMXG5zVGcz6clNSmqlRdZpuZQVxF3Feuv9U8p2Yrs0m4JE0fdvg-SKmsYXTNIPTI
Content-Type: application/json

{
  "id": 57,
  "valor": 90,
  "tipoId": 4,
  "valMin": 10,
  "valMax": 40,
  "bateria": 72
}

###Desassociar um Sensor de uma Embalagem #
DELETE http://localhost:3001/backend/api/embalagem/15/sensor/20
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDUwNzEsImV4cCI6MTczNzIwODY3MX0.XIRj1FMKGKZpRO72rDmefk2uiikl-KFWLQlv7aE2r8RUwItdKLLJd2D2Kms3jmcX

################################ Sensor Service ################################

### Get All sensores #
GET http://localhost:3001/backend/api/sensor/
Accept: application/json

### Patch Sensor Estado #
PATCH http://localhost:3001/backend/api/sensor/2
Accept: application/json
Content-Type: application/json


### Post Leitura Sensor #
POST http://localhost:3001/backend/api/sensor/
Accept: application/json
Content-Type: application/json

{
  "id_sensor": 1,
  "bateria": 72,
  "valor": "40"
}

### Get All Tipos de Sensor #
GET http://localhost:3001/backend/api/sensor/tipo
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDI0OTQsImV4cCI6MTczNzIwNjA5NH0.5Fz-8IE0jFGOJkoGvNZMCUexf1dx09rV_WjI659xhEFM7cUSt-3KXFth4tvVDIwA


### GET All Ultimo Valor dos Sensores por Tipo #
GET http://localhost:3001/backend/api/sensor/GPS
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM3MjAxMDM4LCJleHAiOjE3MzcyMDQ2Mzh9.yjFsYX4Se2RmoG7RMDWjo_kgentkro9bd0aKnqQpmp9phUtQNTQ_vCNrHCl3HjWL


### GET Ver Alertas de um sensor #
GET http://localhost:3001/backend/api/sensor/1/alerta
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM3MjAwMzUzLCJleHAiOjE3MzcyMDM5NTN9.SFiRWTqx1-JPJw8pCZg83ygiNj7HfvTYfaY5i6_N31Uv5VyRvTVRXPEUdElF4dJk

### GET Ver Leituras de um sensor #
GET http://localhost:3001/backend/api/sensor/1/leitura
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM3MjA2NTY0LCJleHAiOjE3MzcyMTAxNjR9.-30Zou8ODm2eKVxpJKgrq1h5pmE0RKur8rybYNc7cIq5gSDy7mvld_xHpnOKq1wQ

################################ EMBALAGENS ###################################

### Get All Tipos de Embalagens #
GET http://localhost:3001/backend/api/embalagem/tipo
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDQ4ODQsImV4cCI6MTczNzIwODQ4NH0.AXYgm5NMJufpGm1qiWCd2UjC2UuseIVgqSQt5PJne-Tw44Nwzvr3SXUwE9-AdEAH

################################ End Points Login ################################

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#
                     #Falar no word falar nos extras#
                     #Criar produtos, criar tipo de embalagens, criar tipo de sensores#
                     #importação de dados de configuração através de ficheiros CSV#
                     #   #
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#

### REQUEST JWT TOKEN
POST http://localhost:3001/backend/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Miguel",
  "password": "123"
}

### Bernardo -> Cliente
### Miguel -> Logista
### Delgado -> Operacional

### GET User Info
GET http://localhost:3001/backend/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcxOTYyNTUsImV4cCI6MTczNzE5OTg1NX0.7Qemlf51fAzy1KzTD8B4oYq69zs4ntHDvwhyLOszt36ZD_qkGy8BElDBxLU5l98N


################################ Endpoints Extra  ################################
### Criar um novo produto
POST http://localhost:3001/backend/api/produto
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcwNjQxMzcsImV4cCI6MTczNzA2NzczN30.8z2oCekahB_ApWUpHr7l7upNo10ROtd5OqX5o3MzwRrPTSREHSqa8l7u7HhhC2SP
Content-Type: application/json
Accept: application/json

{
   "id": 535,
   "nome": "Sapatos",
   "id_categoria": "6"
}

### Get Categorias
GET http://localhost:3001/backend/api/categoria
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDU0NjIsImV4cCI6MTczNzIwOTA2Mn0.GCm27ehk508nWcIitvQlhjBInsI_Tj-xxN4Jqo3DiJGo_yV8xdf0BNcayOun2fDu

### Criar novo tipo de sensor
POST http://localhost:3001/backend/api/sensor/tipo
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcyMDY0NzcsImV4cCI6MTczNzIxMDA3N30.zK25pFnBlik7t4c6UGuSG0dZy2rmDSzN-Wx2NmeWoTiGQSLCygpM4vB4gjAJnwsR
Content-Type: application/json
Accept: application/json

{
  "id": "10",
  "tipo": "Humidade"
}

### Criar novo tipo de embalagem
POST http://localhost:3001/backend/api/embalagem/tipo
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzcwNzAwMTcsImV4cCI6MTczNzA3MzYxN30.UQZJkP34XiR5bY0LhwcBu8nbM-Ygic9xodVUZNFewtdla4YmG8-84MuXBcStNCSO
Content-Type: application/json
Accept: application/json

{
  "id": "1",
  "tipo": "E_TPP",
  "tipos_sensores": [
    { "id": 1 },
    { "id": 1 },
    { "id": 3 }
  ]
}
