
#########################################################################
######################### Novos Endpoints ###############################
#########################################################################

######################### Produtos Service ################################
### GET All Ultimo Valor dos Sensores por Tipo #
GET http://localhost:3001/backend/api/produtos
Accept: application/json

######################### Clientes Service ################################
### GET All clientes #
GET http://localhost:3001/backend/api/clientes
Accept: application/json

######################### Encomenda Service ################################
### Get All Encomenda #
GET http://localhost:3001/backend/api/encomendas/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTMyNTE2MCwiZXhwIjoxNzM1MzI4NzYwfQ.-oP2IsF8YR3kE9f98tOA6Q6BU5LI-JRkFQtK7DbeoZTTHBIAbtms1PF3f_Io8B3g

### Get Encomenda Por Id
GET http://localhost:3001/backend/api/encomendas/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTMyNTE2MCwiZXhwIjoxNzM1MzI4NzYwfQ.-oP2IsF8YR3kE9f98tOA6Q6BU5LI-JRkFQtK7DbeoZTTHBIAbtms1PF3f_Io8B3g


### Get All Encomendas por um determinado estado "PorEntregar" "Cancelada" "EmProcessamento" "Entregue" #
GET http://localhost:3001/backend/api/encomendas/estado/PorEntregar
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTMyNTU3OSwiZXhwIjoxNzM1MzI5MTc5fQ.sLJvK5t8rzdYn0eQYlHggaNlDtvTUjVdFjw5gLIjmZ57b2hvo_3UIeAp9LCElSC4

### Get Encomendas Pendentes #
GET http://localhost:3001/backend/api/encomendas/pendentes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJEZWxnYWRvIiwiaWF0IjoxNzM1MzI2MDg2LCJleHAiOjE3MzUzMjk2ODZ9.JL2tSOpAOErLxlSBq6aY27xVY3Rpca-Vl45L1oERFtXSZ3ppVWY1LR4Q-jL0FlmI

### Alterar estado de uma encomenda
PATCH http://localhost:3001/backend/api/encomendas/1
Accept: application/json
Content-Type: application/json

{
  "estado": "Cancelada"
}

###Criar uma nova encomenda
POST http://localhost:3001/backend/api/encomendas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNaWd1ZWwiLCJpYXQiOjE3MzUyOTQ1MDEsImV4cCI6MTczNTI5ODEwMX0.t2WJKOZc7SpoD80s0hhW8Jyy5XiB95qEn8aJ84rKUFLBxKXrDBGFuBVT_w_IKSlW
Content-Type: application/json

{
  "username": "Bernardo",
  "estado": "PorEntregar",
  "data_expedicao": "2024-10-31T10:00:00",
  "data_entrega": "2024-11-05T10:00:00",
  "produtos": [
    {
      "id": 1,
      "quantidade_por_volume": 10
    },
    {
      "id": 2,
      "quantidade_por_volume": 10
    }
  ]
}

### Associar um volume a uma encomenda
POST http://localhost:3001/backend/api/encomendas/6/volume
Accept: application/json
Content-Type: application/json

{
  "id_produto": 7,
  "quantidade": 2
}

### Get All Alertas de Encomenda por Id #
GET http://localhost:3001/backend/api/encomendas/1/alertas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTMyNTU3OSwiZXhwIjoxNzM1MzI5MTc5fQ.sLJvK5t8rzdYn0eQYlHggaNlDtvTUjVdFjw5gLIjmZ57b2hvo_3UIeAp9LCElSC4

### GET Ver Alertas de encomendas (PorEntregar)
GET http://localhost:3001/backend/api/encomendas/alertas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTMyNTU3OSwiZXhwIjoxNzM1MzI5MTc5fQ.sLJvK5t8rzdYn0eQYlHggaNlDtvTUjVdFjw5gLIjmZ57b2hvo_3UIeAp9LCElSC4


### Get Coordenadas Volumes
GET http://localhost:3001/backend/api/encomendas/1/coordenadas
Accept: application/json

######################### Volume Service ################################

### Get Detalhes Volume
GET http://localhost:3001/backend/api/volume/3
Accept: application/json

###Associar um Sensor a uma Embalagem
POST http://localhost:3001/backend/api/embalagem/3/sensor
Accept: application/json
Content-Type: application/json

{
  "valor": 90,
  "tipoId": 4,
  "estado": "ativo",
  "bateria": 72
}

################################ Sensor Service ################################

### Get All sensores #
GET http://localhost:3001/backend/api/sensor/
Accept: application/json

### Criar um alerta #
POST http://localhost:3001/backend/api/sensor/
Accept: application/json
Content-Type: application/json

{
  "mensagem": "Temperatura elevada, aaaacomida a estragar-se",
  "id_sensor": 5,
  "valor": 40,
  "id_volume": 4
}

### Patch Sensor Estado #
PATCH http://localhost:3001/backend/api/sensor/2/desativar
Accept: application/json
Content-Type: application/json

{
  "estado": "inativo"
}

### Patch Sensor Valor #
PATCH http://localhost:3001/backend/api/sensor/1
Accept: application/json
Content-Type: application/json

{
  "valor": "26.5",
  "bateria": 72
}

### Get All Tipos de Sensor #
GET http://localhost:3001/backend/api/sensor/tipos
Accept: application/json

### GET All Ultimo Valor dos Sensores por Tipo #
GET http://localhost:3001/backend/api/sensor/Temperatura
Accept: application/json

### GET Ver Alertas de um sensor #
GET http://localhost:3001/backend/api/sensor/1/alertas
Accept: application/json

################################ End Points Login ################################

### REQUEST JWT TOKEN #
POST http://localhost:3001/backend/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Delgado", "password": "123" }

### GET User Info #
GET http://localhost:3001/backend/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJCZXJuYXJkbyIsImlhdCI6MTczNTMyNTU3OSwiZXhwIjoxNzM1MzI5MTc5fQ.sLJvK5t8rzdYn0eQYlHggaNlDtvTUjVdFjw5gLIjmZ57b2hvo_3UIeAp9LCElSC4
